### ISSUE TITLE
Failed simulation

### ISSUE THREAD

**Issue by kohl-carmen** [jonescompneurolab/hnn#109]
(hnn) C:\Users\ckohl\hnn>python hnn.py
Starting simulation (6 cores). . .
Starting simulation (6 cores). . .
Terminating simulation. . .
INFO: Failed starting mpiexec, retrying with 3 cores
Traceback (most recent call last):
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 2516, in stopsim
    self.parent().stopsim()
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 3289, in stopsim
    self.runthread.stop() # killed = True # terminate()
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 197, in stop
    self.killproc()
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 240, in killproc
    kill_and_check_nrniv_procs()
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 136, in kill_and_check_nrniv_procs
    print("ERROR: failed to kill nrniv process(es) %s"%pids.join(','))
AttributeError: 'list' object has no attribute 'join'

**Comment by blakecaldwell** [comment]
Thanks @kohl-carmen -- this should prevent the exception from happening that will crash HNN. However, the fact that this happened at all means Windows is having trouble stopping the NEURON processes. If you see the error message, "ERROR: failed to kill nrniv process(es) ", please let me know in a new issue. At least it won't stop HNN now...
