### ISSUE TITLE
Optimization crashes with cannot serialize '_io.BufferedReader' object

### ISSUE THREAD

**Issue by blakecaldwell** [jonescompneurolab/hnn#136]
This bug appeared in the past month, probably a result of a change in a python library. Not related to NERUON upgrade from 7.6 to 7.7 or related to running in a docker container.

Starting model optimization. . .
Traceback (most recent call last):
  File "/home/hnn_user/hnn_source_code/hnn_qt5.py", line 214, in run
    self.optmodel() # run optimization
  File "/home/hnn_user/hnn_source_code/hnn_qt5.py", line 374, in optmodel
    simdat.initial_ddat = deepcopy(simdat.ddat)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: cannot serialize '_io.BufferedReader' object
/home/hnn_user/start_hnn.sh: line 42:    38 Aborted                 python3 hnn.py

**Comment by blakecaldwell** [comment]
Fixed by f52833 and 59749a
