### ISSUE TITLE
Crash when running optimization on specific parameter file

### ISSUE THREAD

**Issue by blakecaldwell** [jonescompneurolab/hnn#173]
When starting the third round of optimization for the tutorial, the "Failed simulation" dialog will pop up after a running the very first trial. It appears to be specific to the parameters that are set. 

Error message:
```
Starting model optimization. . .
Optimization step 1, simulation 1
Simulation exited with return code -11. Stderr from console:
0 nrniv: Vector Vector argument to .add() wrong size

0  near line 0
0  dp_total_L5 = 0.
^
0 Vector[1].add(...)
2 nrniv: Vector Vector argument to .add() wrong size

2  near line 0
2  dp_total_L5 = 0.
^
3 nrniv: Vector Vector argument to .add() wrong size

3  near line 0
3  dp_total_L5 = 0.
^
3 Vector[1].add(...)
6 nrniv: Vector Vector argument to .add() wrong size

6  near line 0
6  dp_total_L5 = 0.
^
6 Vector[1].add(...)
7 nrniv: Vector Vector argument to .add() wrong size

7  near line 0
7  dp_total_L5 = 0.
^
1 nrniv: Vector Vector argument to .add() wrong size

1  near line 0
1  dp_total_L5 = 0.
^
1 Vector[1].add(...)
2 Vector[1].add(...)
4 nrniv: Vector Vector argument to .add() wrong size

4  near line 0
4  dp_total_L5 = 0.
^
4 Vector[1].add(...)
5 nrniv: Vector Vector argument to .add() wrong size

5  near line 0
5  dp_total_L5 = 0.
^
5 Vector[1].add(...)
7 Vector[1].add(...)
Traceback (most recent call last):
File "run.py", line 467, in <module>
if ntrial > 1: runtrials(ntrial,p['inc_evinput'])
File "run.py", line 369, in runtrials
runsim() # run the simulation
File "run.py", line 435, in runsim
net.aggregate_currents() # aggregate the currents independently on each proc
File "/Users/blake/repos/hnn-new/network.py", line 387, in aggregate_currents
self.current['L2Pyr_soma'].add(I_soma)
RuntimeError: hoc error
Traceback (most recent call last):
File "run.py", line 467, in <module>
if ntrial > 1: runtrials(ntrial,p['inc_evinput'])
File "run.py", line 369, in runtrials
runsim() # run the simulation
File "run.py", line 435, in runsim
net.aggregate_currents() # aggregate the currents independently on each proc
File "/Users/blake/repos/hnn-new/network.py", line 387, in aggregate_currents
self.current['L2Pyr_soma'].add(I_soma)
RuntimeError: hoc error
Traceback (most recent call last):
File "run.py", line 467, in <module>
if ntrial > 1: runtrials(ntrial,p['inc_evinput'])
File "run.py", line 369, in runtrials
runsim() # run the simulation
File "run.py", line 435, in runsim
net.aggregate_currents() # aggregate the currents independently on each proc
File "/Users/blake/repos/hnn-new/network.py", line 387, in aggregate_currents
self.current['L2Pyr_soma'].add(I_soma)
RuntimeError: hoc error
Traceback (most recent call last):
File "run.py", line 467, in <module>
if ntrial > 1: runtrials(ntrial,p['inc_evinput'])
File "run.py", line 369, in runtrials
runsim() # run the simulation
File "run.py", line 435, in runsim
net.aggregate_currents() # aggregate the currents independently on each proc
File "/Users/blake/repos/hnn-new/network.py", line 387, in aggregate_currents
self.current['L2Pyr_soma'].add(I_soma)
RuntimeError: hoc error
Traceback (most recent call last):
File "run.py", line 467, in <module>
if ntrial > 1: runtrials(ntrial,p['inc_evinput'])
File "run.py", line 369, in runtrials
runsim() # run the simulation
File "run.py", line 435, in runsim
net.aggregate_currents() # aggregate the currents independently on each proc
File "/Users/blake/repos/hnn-new/network.py", line 387, in aggregate_currents
self.current['L2Pyr_soma'].add(I_soma)
RuntimeError: hoc error
Traceback (most recent call last):
File "run.py", line 467, in <module>
if ntrial > 1: runtrials(ntrial,p['inc_evinput'])
File "run.py", line 369, in runtrials
runsim() # run the simulation
File "run.py", line 435, in runsim
net.aggregate_currents() # aggregate the currents independently on each proc
File "/Users/blake/repos/hnn-new/network.py", line 387, in aggregate_currents
self.current['L2Pyr_soma'].add(I_soma)
RuntimeError: hoc error
Traceback (most recent call last):
File "run.py", line 467, in <module>
if ntrial > 1: runtrials(ntrial,p['inc_evinput'])
File "run.py", line 369, in runtrials
runsim() # run the simulation
File "run.py", line 435, in runsim
net.aggregate_currents() # aggregate the currents independently on each proc
File "/Users/blake/repos/hnn-new/network.py", line 387, in aggregate_currents
self.current['L2Pyr_soma'].add(I_soma)
RuntimeError: hoc error
Traceback (most recent call last):
File "run.py", line 467, in <module>
if ntrial > 1: runtrials(ntrial,p['inc_evinput'])
File "run.py", line 369, in runtrials
runsim() # run the simulation
File "run.py", line 435, in runsim
net.aggregate_currents() # aggregate the currents independently on each proc
File "/Users/blake/repos/hnn-new/network.py", line 387, in aggregate_currents
self.current['L2Pyr_soma'].add(I_soma)
RuntimeError: hoc error
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
[MacBook-Pro:55313] *** Process received signal ***
[MacBook-Pro:55313] Signal: Segmentation fault: 11 (11)
[MacBook-Pro:55313] Signal code:  (0)
[MacBook-Pro:55313] Failing at address: 0x0
[MacBook-Pro:55313] [ 0] 0   libsystem_platform.dylib            0x00007fff6fedb42d _sigtramp + 29
[MacBook-Pro:55313] [ 1] 0   ???                                 0x0000000116f5a798 0x0 + 4680165272
[MacBook-Pro:55313] [ 2] 0   mca_pmix_pmix3x.so                  0x0000000107856ca6 OPAL_MCA_PMIX3X_pmix_ptl_base_recv_handler + 1302
[MacBook-Pro:55313] [ 3] 0   libopen-pal.40.dylib                0x0000000107674c38 opal_libevent2022_event_base_loop + 2040
[MacBook-Pro:55313] [ 4] 0   mca_pmix_pmix3x.so                  0x000000010781c2be progress_engine + 30
[MacBook-Pro:55313] [ 5] 0   libsystem_pthread.dylib             0x00007fff6fee6e65 _pthread_start + 148
[MacBook-Pro:55313] [ 6] 0   libsystem_pthread.dylib             0x00007fff6fee283b thread_start + 15
[MacBook-Pro:55313] *** End of error message ***
```

Parameter settings:
```
$ diff -u ~/repos/hnn-new/param/default.param ERPYes3Trials_173ms_opt3.param 
--- /Users/blake/repos/hnn-new/param/default.param	2019-11-26 12:18:38.000000000 -0500
+++ ERPYes3Trials_173ms_opt3.param	2020-01-07 12:28:33.000000000 -0500
@@ -1,9 +1,9 @@
-sim_prefix: default
-expmt_groups: {default}
-tstop: 170
+sim_prefix: ERPYes3Trials_173ms_opt3
+expmt_groups: {ERPYes3Trials_173ms_opt3}
+tstop: 173.325
 dt: 0.025
 celsius: 37.0
-N_trials: 1
+N_trials: 3
 threshold: 0.0
 save_figs: 0
 save_spec_data: 0
@@ -11,7 +11,7 @@
 dipole_scalefctr: 3000
 dipole_smooth_win: 30
 save_vsoma: 0
-prng_seedcore_opt: 0
+prng_seedcore_opt: 1
 prng_seedcore_input_prox: 4
 prng_seedcore_input_dist: 4
 prng_seedcore_extpois: 4
@@ -20,6 +20,7 @@
 prng_seedcore_evdist_1: 4
 prng_seedcore_evprox_2: 4
 prng_seedcore_evdist_2: 0
+spec_cmap: jet
 L2Pyr_soma_L: 22.1
 L2Pyr_soma_diam: 23.4
 L2Pyr_soma_cm: 0.6195
@@ -165,37 +166,37 @@
 input_dist_A_weight_L5Pyr_ampa: 0.0
 input_dist_A_weight_L5Pyr_nmda: 0.0
 input_dist_A_delay_L5: 5.0
-t_evprox_1: 26.61
-sigma_t_evprox_1: 2.47
+t_evprox_1: 18.977317
+sigma_t_evprox_1: 3.682554
 numspikes_evprox_1: 1
-gbar_evprox_1_L2Pyr_ampa: 0.01525
-gbar_evprox_1_L2Pyr_nmda: 0.0
-gbar_evprox_1_L2Basket_ampa: 0.08831
-gbar_evprox_1_L2Basket_nmda: 0.0
-gbar_evprox_1_L5Pyr_ampa: 0.00865
-gbar_evprox_1_L5Pyr_nmda: 0.0
-gbar_evprox_1_L5Basket_ampa: 0.19934
-gbar_evprox_1_L5Basket_nmda: 0.0
-t_evdist_1: 63.53
-sigma_t_evdist_1: 3.85
+gbar_evprox_1_L2Pyr_ampa: 0.033945
+gbar_evprox_1_L2Pyr_nmda: 0.000086
+gbar_evprox_1_L2Basket_ampa: 0.274861
+gbar_evprox_1_L2Basket_nmda: 0.364855
+gbar_evprox_1_L5Pyr_ampa: 0.03423
+gbar_evprox_1_L5Pyr_nmda: 0
+gbar_evprox_1_L5Basket_ampa: 0.624393
+gbar_evprox_1_L5Basket_nmda: 0.375863
+t_evdist_1: 63.220155
+sigma_t_evdist_1: 3.795375
 numspikes_evdist_1: 1
-gbar_evdist_1_L2Pyr_ampa: 0.000007
-gbar_evdist_1_L2Pyr_nmda: 0.004317
-gbar_evdist_1_L2Basket_ampa: 0.006562
-gbar_evdist_1_L2Basket_nmda: 0.019482
-gbar_evdist_1_L5Pyr_ampa: 0.142300
-gbar_evdist_1_L5Pyr_nmda: 0.080074
-t_evprox_2: 137.12
-sigma_t_evprox_2: 8.33
+gbar_evdist_1_L2Pyr_ampa: 0.000022
+gbar_evdist_1_L2Pyr_nmda: 0.043572
+gbar_evdist_1_L2Basket_ampa: 0.0167
+gbar_evdist_1_L2Basket_nmda: 0.205952
+gbar_evdist_1_L5Pyr_ampa: 0.815666
+gbar_evdist_1_L5Pyr_nmda: 0.076704
+t_evprox_2: 120.475139
+sigma_t_evprox_2: 9.996456
 numspikes_evprox_2: 1
-gbar_evprox_2_L2Pyr_ampa: 1.438840
-gbar_evprox_2_L2Pyr_nmda: 0.0
-gbar_evprox_2_L2Basket_ampa: 0.000003
-gbar_evprox_2_L2Basket_nmda: 0.0
-gbar_evprox_2_L5Pyr_ampa: 0.684013
-gbar_evprox_2_L5Pyr_nmda: 0.0
-gbar_evprox_2_L5Basket_ampa: 0.008958
-gbar_evprox_2_L5Basket_nmda: 0.0
+gbar_evprox_2_L2Pyr_ampa: 2.798832
+gbar_evprox_2_L2Pyr_nmda: 0.015651
+gbar_evprox_2_L2Basket_ampa: 0.000005
+gbar_evprox_2_L2Basket_nmda: 0.397462
+gbar_evprox_2_L5Pyr_ampa: 2.449362
+gbar_evprox_2_L5Pyr_nmda: 0.067545
+gbar_evprox_2_L5Basket_ampa: 0.010116
+gbar_evprox_2_L5Basket_nmda: 0.062405
 sync_evinput: 0
 inc_evinput: 0.0
 L2Pyr_Pois_A_weight_ampa: 0.0
```

Adding some debug statements around the .add() function indicate that vectors indeed have different sizes. The value for `size1` is for `self.current['L2Pyr_soma']`.
```
L2_pyramidal: size1=3744, I_soma.size=3743.000000
L2_pyramidal: size1=3744, I_soma.size=3743.000000
L2_pyramidal: size1=3744, I_soma.size=3743.000000
L2_pyramidal: size1=3744, I_soma.size=3743.000000
L2_pyramidal: size1=3744, I_soma.size=3743.000000
L2_pyramidal: size1=3744, I_soma.size=3743.000000
L2_pyramidal: size1=3744, I_soma.size=3743.000000
L2_pyramidal: size1=3744, I_soma.size=3743.000000
```

They should be equal, but the actual size can vary:
default.param
```
L2_pyramidal: size1=4586, I_soma.size=4586.000000
L2_pyramidal: size1=4586, I_soma.size=4586.000000
L2_pyramidal: size1=4586, I_soma.size=4586.000000
L2_pyramidal: size1=4586, I_soma.size=4586.000000
L2_pyramidal: size1=4586, I_soma.size=4586.000000
L2_pyramidal: size1=4586, I_soma.size=4586.000000
L2_pyramidal: size1=4586, I_soma.size=4586.000000
L2_pyramidal: size1=4586, I_soma.size=4586.000000
L2_pyramidal: size1=4586, I_soma.size=4586.000000
L2_pyramidal: size1=4586, I_soma.size=4586.000000
L2_pyramidal: size1=4586, I_soma.size=4586.000000
L2_pyramidal: size1=4586, I_soma.size=4586.000000
```

**Comment by blakecaldwell** [comment]
Depended on by https://github.com/jonescompneurolab/hnn-tutorials/pull/1

**Comment by blakecaldwell** [comment]
Closing. No longer observe this issue after hnn-core integration
