### ISSUE TITLE
Scripting multiple simulations 

### ISSUE THREAD

**Issue by tbardouille** [jonescompneurolab/hnn#214]
Hi there,
 
I’m interested in running a reasonably large number of HNN simulations with different parameters (to fine tune some of my model configuration). It would be impracticable to do this by point and click in the GUI.
 
Is it possible for me to make a Python (or shell) script to run this large number of simulations? If so, can you advise my how to do so?
 
I’ve looked at some files in the GitHub repo (including in the scripts folder) but couldn’t find anything that I could get working without errors. Nor could I find any documentation regarding scripting. If this information does exist, I apologize for the e-mail. Can you please point me in the correct direction?
 
Note: I’m working on a Mac, but also have access to a Linux machine.
 
Thanks,
Tim.

**Comment by jasmainak** [comment]
You might be interested in https://github.com/jonescompneurolab/hnn-core

**Comment by blakecaldwell** [comment]
@tbardouille Here's the workaround for HNN right now. It's a workaround until hnn-core is integrated with HNN. Hence, the lack of documentation. Note, that if you use hnn-core right now, each simulation trial will only run on a single core.

1. Generate individual parameter files for each parameter combination. Additionally, change the `sim_prefix` parameter to be unique for each file.

2. Script running HNN's run.py over the different files. The number of trials can be specified in the .param file or on the command line via `ntrial 3`.
```
mpiexec -np 16 nrniv -mpi -python -nobanner run.py param/default.param

3. Terminal output will be similar to the simulation log in the GUI. Results will be saved in `~/hnn_out/data/[sim prefix]/`

4. View results in the GUI with the 'Set Parameters from File` button and choosing the appropriate parameter file in `~/hnn_out/param/[sim prefix]/`

**Comment by tbardouille** [comment]
Thanks for the advice. I installed Open-MPI on my Mac (v 4.0.4) so that I can run mpiexec. This installed fine, and I made a copy of AlphaAndBeta.param to test with. However, I have a problem when I run run.py, as follows (with standard output shown).

Any advice would be appreciated. Thanks.

$ mpiexec -np 4 nrniv -mpi -python -nobanner run.py param/AlphaAndBeta_testScript.param
numprocs=4
making dout: /Users/tbardouille/hnn_out/data/AlphaAndBeta
>>> >>> >>> >>> Traceback (most recent call last):
  File "run.py", line 254, in <module>
    net = network.NetworkOnNode(p) # create node-specific network
  File "/Users/tbardouille/GitHub/hnn/network.py", line 92, in __init__
    self.__create_all_src()
  File "/Users/tbardouille/GitHub/hnn/network.py", line 296, in __create_all_src
    self.cells.append(L2Basket(gid, pos))
  File "/Users/tbardouille/GitHub/hnn/L2_basket.py", line 22, in __init__
    self.__biophysics()
  File "/Users/tbardouille/GitHub/hnn/L2_basket.py", line 32, in __biophysics
    self.soma.insert('hh2')
ValueError: argument not a density mechanism name.

Traceback (most recent call last):
  File "run.py", line 254, in <module>
    net = network.NetworkOnNode(p) # create node-specific network
  File "/Users/tbardouille/GitHub/hnn/network.py", line 92, in __init__
    self.__create_all_src()
  File "/Users/tbardouille/GitHub/hnn/network.py", line 296, in __create_all_src
    self.cells.append(L2Basket(gid, pos))
  File "/Users/tbardouille/GitHub/hnn/L2_basket.py", line 22, in __init__
    self.__biophysics()
  File "/Users/tbardouille/GitHub/hnn/L2_basket.py", line 32, in __biophysics
    self.soma.insert('hh2')
ValueError: argument not a density mechanism name.

Traceback (most recent call last):
  File "run.py", line 254, in <module>
    net = network.NetworkOnNode(p) # create node-specific network
  File "/Users/tbardouille/GitHub/hnn/network.py", line 92, in __init__
    self.__create_all_src()
  File "/Users/tbardouille/GitHub/hnn/network.py", line 296, in __create_all_src
    self.cells.append(L2Basket(gid, pos))
  File "/Users/tbardouille/GitHub/hnn/L2_basket.py", line 22, in __init__
    self.__biophysics()
  File "/Users/tbardouille/GitHub/hnn/L2_basket.py", line 32, in __biophysics
    self.soma.insert('hh2')
ValueError: argument not a density mechanism name.


Traceback (most recent call last):
  File "run.py", line 254, in <module>
    net = network.NetworkOnNode(p) # create node-specific network
  File "/Users/tbardouille/GitHub/hnn/network.py", line 92, in __init__
    self.__create_all_src()
  File "/Users/tbardouille/GitHub/hnn/network.py", line 296, in __create_all_src
    self.cells.append(L2Basket(gid, pos))
  File "/Users/tbardouille/GitHub/hnn/L2_basket.py", line 22, in __init__
    self.__biophysics()
  File "/Users/tbardouille/GitHub/hnn/L2_basket.py", line 32, in __biophysics
    self.soma.insert('hh2')
ValueError: argument not a density mechanism name.
>>>

**Comment by blakecaldwell** [comment]
@tbardouille I suspect this is from the NEURON .mod files not getting compiled. After typing `make` on a mac/linux in the hnn directory, there should be a folder `x86_64`. Is that the case?

You may have already seen these instructions, but in case they are of help, here's the link:
https://jonescompneurolab.github.io/hnn/installer/mac/native_install.html

**Comment by blakecaldwell** [comment]
Please let us know if you are still having this issue. Closing for now.

**Comment by tbardouille** [comment]
I couldn't get this to work on our Linux server, so I ended up going with hnn-core. That works well on the Linux server. Thanks!
