### ISSUE TITLE
"go to previous simulation" did not work

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn#287]
I got the following exception:

```py
Traceback (most recent call last):
  File "hnn.py", line 19, in <module>
    runqt5()
  File "hnn.py", line 15, in runqt5
    sys.exit(app.exec_())
  File "/Users/mainak/Documents/github_repos/hnn/hnn/qt_main.py", line 489, in prevSim
    self.updateSelectedSim(new_simidx)
  File "/Users/mainak/Documents/github_repos/hnn/hnn/qt_main.py", line 461, in updateSelectedSim
    self.updateDatCanv(params)
  File "/Users/mainak/Documents/github_repos/hnn/hnn/qt_main.py", line 444, in updateDatCanv
    self.initSimCanvas()  # recreate canvas
  File "/Users/mainak/Documents/github_repos/hnn/hnn/qt_main.py", line 894, in initSimCanvas
    raise self.sim_canvas.saved_exception
  File "/Users/mainak/Documents/github_repos/hnn/hnn/qt_sim.py", line 57, in __init__
    self.plot()
  File "/Users/mainak/Documents/github_repos/hnn/hnn/qt_sim.py", line 443, in plot
    self.plotsimdat()  # creates self.axdipole
  File "/Users/mainak/Documents/github_repos/hnn/hnn/qt_sim.py", line 350, in plotsimdat
    trials, self.params)
  File "/Users/mainak/Documents/github_repos/hnn/hnn/spikefn.py", line 47, in __init__
    if 'common' in self.gid_ranges:
TypeError: argument of type 'NoneType' is not iterable
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Users/mainak/Documents/github_repos/hnn/hnn/qt_sim.py", line 57, in __init__
    self.plot()
  File "/Users/mainak/Documents/github_repos/hnn/hnn/qt_sim.py", line 443, in plot
    self.plotsimdat()  # creates self.axdipole
  File "/Users/mainak/Documents/github_repos/hnn/hnn/qt_sim.py", line 350, in plotsimdat
    trials, self.params)
  File "/Users/mainak/Documents/github_repos/hnn/hnn/spikefn.py", line 47, in __init__
    if 'common' in self.gid_ranges:
TypeError: argument of type 'NoneType' is not iterable

Original exception was:
Traceback (most recent call last):
  File "/Users/mainak/Documents/github_repos/hnn/hnn/qt_main.py", line 489, in prevSim
    self.updateSelectedSim(new_simidx)
  File "/Users/mainak/Documents/github_repos/hnn/hnn/qt_main.py", line 461, in updateSelectedSim
    self.updateDatCanv(params)
  File "/Users/mainak/Documents/github_repos/hnn/hnn/qt_main.py", line 444, in updateDatCanv
    self.initSimCanvas()  # recreate canvas
  File "/Users/mainak/Documents/github_repos/hnn/hnn/qt_main.py", line 894, in initSimCanvas
    raise self.sim_canvas.saved_exception
  File "/Users/mainak/Documents/github_repos/hnn/hnn/qt_sim.py", line 57, in __init__
    self.plot()
  File "/Users/mainak/Documents/github_repos/hnn/hnn/qt_sim.py", line 443, in plot
    self.plotsimdat()  # creates self.axdipole
  File "/Users/mainak/Documents/github_repos/hnn/hnn/qt_sim.py", line 350, in plotsimdat
    trials, self.params)
  File "/Users/mainak/Documents/github_repos/hnn/hnn/spikefn.py", line 47, in __init__
    if 'common' in self.gid_ranges:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by blakecaldwell** [comment]
It worked for me with master. @jasmainak if you could please confirm this is fixed now.

**Comment by jasmainak** [comment]
I confirm this works now. Thanks a lot @blakecaldwell !
