### ISSUE TITLE
error starting gui on maint/pre-hnn-core branch

### ISSUE THREAD

**Issue by rythorpe** [jonescompneurolab/hnn#305]
I got the following traceback when trying to open the HNN GUI on our legacy branch. This is weird because it was working for me last week before I fetched the master branch. Any idea what is going on here?

(hnn) ryan@rv02:~/hnn$ python hnn.py
Traceback (most recent call last):
  File "hnn.py", line 37, in <module>
    runqt5()
  File "hnn.py", line 26, in runqt5
    ex = HNNGUI()
  File "/home/ryan/hnn/hnn_qt5.py", line 3347, in __init__
    self.initUI()
  File "/home/ryan/hnn/hnn_qt5.py", line 4028, in initUI
    self.initSimCanvas(gRow=gRow, reInit=False)
  File "/home/ryan/hnn/hnn_qt5.py", line 4104, in initSimCanvas
    self.m = SIMCanvas(paramf, parent = self, width=10, height=1, dpi=getmplDPI(), optMode=optMode) # also loads data
  File "/home/ryan/hnn/simdat.py", line 276, in __init__
    self.plot()
  File "/home/ryan/hnn/simdat.py", line 756, in plot
    self.plotsimdat()  # creates self.axdipole
  File "/home/ryan/hnn/simdat.py", line 620, in plotsimdat
    xo = self.plotinputhist(xl, dinty)
  File "/home/ryan/hnn/simdat.py", line 297, in plotinputhist
    extinputs = spikefn.ExtInputs(dfile['spk'], dfile['outparam'])
  File "/home/ryan/hnn/spikefn.py", line 75, in __init__
    self.gid_prox, self.gid_dist = self.__get_extinput_gids()
  File "/home/ryan/hnn/spikefn.py", line 86, in __get_extinput_gids
    if len(self.gid_dict['extinput']) == 2:
KeyError: 'extinput'

**Comment by rythorpe** [comment]
Also, it looks like MPI parallelization isn't working on master yet. Is this a bug or have we just not implemented it yet?

**Comment by rythorpe** [comment]
Apparently pre-hnn-core was trying to load default simulation data produced by the development branch, which caused the key error when trying first start up the GUI. I'm closing the issue.
