### ISSUE TITLE
"Failed Running Sim"

### ISSUE THREAD

**Issue by shatton412** [jonescompneurolab/hnn#334]
Hello, 
I have been trying to run the simulations just from the source parameter files provided, but keeping getting this error "Failed Running Sim."
Below is the code I received with this error. Thanks

Starting simulation (16 cores). . .
INFO: Failed starting mpiexec, retrying with 8 cores
Simulation exited with return code 1. Stderr from console:
NEURON -- VERSION 8.1.0 HEAD (047dd824) 2022-03-25
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2021
See http://neuron.yale.edu/neuron/credits

Additional mechanisms from files
"mod/ar.mod" "mod/beforestep_py.mod" "mod/ca.mod" "mod/cad.mod" "mod/cat.mod" "mod/dipole.mod" "mod/dipole_pp.mod" "mod/hh2.mod" "mod/kca.mod" "mod/km.mod" "mod/lfp.mod" "mod/mea.mod" "mod/vecevent.mod"
Traceback (most recent call last):
File "run.py", line 227, in <module>
p_exp = paramrw.ExpParams(f_psim, debug=debug) # creates p_exp.sim_prefix and other param structures
File "/home/shatton/hnn_source_code/paramrw.py", line 159, in __init__
p_all_input = self.__read_sim(f_psim)
File "/home/shatton/hnn_source_code/paramrw.py", line 206, in __read_sim
lines = fio.clean_lines(f_psim)
File "/home/shatton/hnn_source_code/fileio.py", line 205, in clean_lines
with open(file) as f_in:
FileNotFoundError: [Errno 2] No such file or directory: 'Around.param'
Traceback (most recent call last):
File "run.py", line 227, in <module>
p_exp = paramrw.ExpParams(f_psim, debug=debug) # creates p_exp.sim_prefix and other param structures
File "/home/shatton/hnn_source_code/paramrw.py", line 159, in __init__
p_all_input = self.__read_sim(f_psim)
File "/home/shatton/hnn_source_code/paramrw.py", line 206, in __read_sim
lines = fio.clean_lines(f_psim)
File "/home/shatton/hnn_source_code/fileio.py", line 205, in clean_lines
with open(file) as f_in:
FileNotFoundError: [Errno 2] No such file or directory: 'Around.param'
Traceback (most recent call last):
File "run.py", line 227, in <module>
p_exp = paramrw.ExpParams(f_psim, debug=debug) # creates p_exp.sim_prefix and other param structures
File "/home/shatton/hnn_source_code/paramrw.py", line 159, in __init__
p_all_input = self.__read_sim(f_psim)
File "/home/shatton/hnn_source_code/paramrw.py", line 206, in __read_sim
lines = fio.clean_lines(f_psim)
File "/home/shatton/hnn_source_code/fileio.py", line 205, in clean_lines
with open(file) as f_in:
FileNotFoundError: [Errno 2] No such file or directory: 'Around.param'
Traceback (most recent call last):
File "run.py", line 227, in <module>
p_exp = paramrw.ExpParams(f_psim, debug=debug) # creates p_exp.sim_prefix and other param structures
File "/home/shatton/hnn_source_code/paramrw.py", line 159, in __init__
p_all_input = self.__read_sim(f_psim)
File "/home/shatton/hnn_source_code/paramrw.py", line 206, in __read_sim
lines = fio.clean_lines(f_psim)
File "/home/shatton/hnn_source_code/fileio.py", line 205, in clean_lines
with open(file) as f_in:
FileNotFoundError: [Errno 2] No such file or directory: 'Around.param'
Traceback (most recent call last):
File "run.py", line 227, in <module>
p_exp = paramrw.ExpParams(f_psim, debug=debug) # creates p_exp.sim_prefix and other param structures
File "/home/shatton/hnn_source_code/paramrw.py", line 159, in __init__
p_all_input = self.__read_sim(f_psim)
File "/home/shatton/hnn_source_code/paramrw.py", line 206, in __read_sim
lines = fio.clean_lines(f_psim)
File "/home/shatton/hnn_source_code/fileio.py", line 205, in clean_lines
with open(file) as f_in:
FileNotFoundError: [Errno 2] No such file or directory: 'Around.param'
Traceback (most recent call last):
File "run.py", line 227, in <module>
p_exp = paramrw.ExpParams(f_psim, debug=debug) # creates p_exp.sim_prefix and other param structures
File "/home/shatton/hnn_source_code/paramrw.py", line 159, in __init__
p_all_input = self.__read_sim(f_psim)
File "/home/shatton/hnn_source_code/paramrw.py", line 206, in __read_sim
lines = fio.clean_lines(f_psim)
File "/home/shatton/hnn_source_code/fileio.py", line 205, in clean_lines
with open(file) as f_in:
FileNotFoundError: [Errno 2] No such file or directory: 'Around.param'
Traceback (most recent call last):
File "run.py", line 227, in <module>
p_exp = paramrw.ExpParams(f_psim, debug=debug) # creates p_exp.sim_prefix and other param structures
File "/home/shatton/hnn_source_code/paramrw.py", line 159, in __init__
p_all_input = self.__read_sim(f_psim)
File "/home/shatton/hnn_source_code/paramrw.py", line 206, in __read_sim
lines = fio.clean_lines(f_psim)
File "/home/shatton/hnn_source_code/fileio.py", line 205, in clean_lines
with open(file) as f_in:
FileNotFoundError: [Errno 2] No such file or directory: 'Around.param'
Traceback (most recent call last):
File "run.py", line 227, in <module>
p_exp = paramrw.ExpParams(f_psim, debug=debug) # creates p_exp.sim_prefix and other param structures
File "/home/shatton/hnn_source_code/paramrw.py", line 159, in __init__
p_all_input = self.__read_sim(f_psim)
File "/home/shatton/hnn_source_code/paramrw.py", line 206, in __read_sim
lines = fio.clean_lines(f_psim)
File "/home/shatton/hnn_source_code/fileio.py", line 205, in clean_lines
with open(file) as f_in:
FileNotFoundError: [Errno 2] No such file or directory: 'Around.param'
[Lola:00891] 7 more processes have sent help message help-btl-vader.txt / cma-permission-denied
[Lola:00891] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
Warning: could not read file: /home/shatton/hnn_out/data/Messing Around/dpl.txt
Warning: could not read file: /home/shatton/hnn_out/data/Messing Around/spk.txt
Warning: could not read file: /home/shatton/hnn_out/data/Messing Around/dpl.txt
Warning: could not read file: /home/shatton/hnn_out/data/Messing Around/spk.txt
Starting simulation (16 cores). . .
INFO: Failed starting mpiexec, retrying with 8 cores
Simulation exited with return code 1. Stderr from console:
NEURON -- VERSION 8.1.0 HEAD (047dd824) 2022-03-25
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2021
See http://neuron.yale.edu/neuron/credits

Additional mechanisms from files
"mod/ar.mod" "mod/beforestep_py.mod" "mod/ca.mod" "mod/cad.mod" "mod/cat.mod" "mod/dipole.mod" "mod/dipole_pp.mod" "mod/hh2.mod" "mod/kca.mod" "mod/km.mod" "mod/lfp.mod" "mod/mea.mod" "mod/vecevent.mod"
Traceback (most recent call last):
File "run.py", line 227, in <module>
p_exp = paramrw.ExpParams(f_psim, debug=debug) # creates p_exp.sim_prefix and other param structures
File "/home/shatton/hnn_source_code/paramrw.py", line 159, in __init__
p_all_input = self.__read_sim(f_psim)
File "/home/shatton/hnn_source_code/paramrw.py", line 206, in __read_sim
lines = fio.clean_lines(f_psim)
File "/home/shatton/hnn_source_code/fileio.py", line 205, in clean_lines
with open(file) as f_in:
FileNotFoundError: [Errno 2] No such file or directory: 'Around.param'
Traceback (most recent call last):
File "run.py", line 227, in <module>
p_exp = paramrw.ExpParams(f_psim, debug=debug) # creates p_exp.sim_prefix and other param structures
File "/home/shatton/hnn_source_code/paramrw.py", line 159, in __init__
p_all_input = self.__read_sim(f_psim)
File "/home/shatton/hnn_source_code/paramrw.py", line 206, in __read_sim
lines = fio.clean_lines(f_psim)
File "/home/shatton/hnn_source_code/fileio.py", line 205, in clean_lines
with open(file) as f_in:
FileNotFoundError: [Errno 2] No such file or directory: 'Around.param'
Traceback (most recent call last):
File "run.py", line 227, in <module>
p_exp = paramrw.ExpParams(f_psim, debug=debug) # creates p_exp.sim_prefix and other param structures
File "/home/shatton/hnn_source_code/paramrw.py", line 159, in __init__
p_all_input = self.__read_sim(f_psim)
File "/home/shatton/hnn_source_code/paramrw.py", line 206, in __read_sim
lines = fio.clean_lines(f_psim)
File "/home/shatton/hnn_source_code/fileio.py", line 205, in clean_lines
with open(file) as f_in:
FileNotFoundError: [Errno 2] No such file or directory: 'Around.param'
Traceback (most recent call last):
File "run.py", line 227, in <module>
p_exp = paramrw.ExpParams(f_psim, debug=debug) # creates p_exp.sim_prefix and other param structures
File "/home/shatton/hnn_source_code/paramrw.py", line 159, in __init__
p_all_input = self.__read_sim(f_psim)
File "/home/shatton/hnn_source_code/paramrw.py", line 206, in __read_sim
lines = fio.clean_lines(f_psim)
File "/home/shatton/hnn_source_code/fileio.py", line 205, in clean_lines
with open(file) as f_in:
FileNotFoundError: [Errno 2] No such file or directory: 'Around.param'
Traceback (most recent call last):
File "run.py", line 227, in <module>
p_exp = paramrw.ExpParams(f_psim, debug=debug) # creates p_exp.sim_prefix and other param structures
File "/home/shatton/hnn_source_code/paramrw.py", line 159, in __init__
p_all_input = self.__read_sim(f_psim)
File "/home/shatton/hnn_source_code/paramrw.py", line 206, in __read_sim
lines = fio.clean_lines(f_psim)
File "/home/shatton/hnn_source_code/fileio.py", line 205, in clean_lines
with open(file) as f_in:
FileNotFoundError: [Errno 2] No such file or directory: 'Around.param'
Traceback (most recent call last):
File "run.py", line 227, in <module>
p_exp = paramrw.ExpParams(f_psim, debug=debug) # creates p_exp.sim_prefix and other param structures
File "/home/shatton/hnn_source_code/paramrw.py", line 159, in __init__
p_all_input = self.__read_sim(f_psim)
File "/home/shatton/hnn_source_code/paramrw.py", line 206, in __read_sim
lines = fio.clean_lines(f_psim)
File "/home/shatton/hnn_source_code/fileio.py", line 205, in clean_lines
with open(file) as f_in:
FileNotFoundError: [Errno 2] No such file or directory: 'Around.param'
Traceback (most recent call last):
File "run.py", line 227, in <module>
p_exp = paramrw.ExpParams(f_psim, debug=debug) # creates p_exp.sim_prefix and other param structures
File "/home/shatton/hnn_source_code/paramrw.py", line 159, in __init__
p_all_input = self.__read_sim(f_psim)
File "/home/shatton/hnn_source_code/paramrw.py", line 206, in __read_sim
lines = fio.clean_lines(f_psim)
File "/home/shatton/hnn_source_code/fileio.py", line 205, in clean_lines
with open(file) as f_in:
FileNotFoundError: [Errno 2] No such file or directory: 'Around.param'
Traceback (most recent call last):
File "run.py", line 227, in <module>
p_exp = paramrw.ExpParams(f_psim, debug=debug) # creates p_exp.sim_prefix and other param structures
File "/home/shatton/hnn_source_code/paramrw.py", line 159, in __init__
p_all_input = self.__read_sim(f_psim)
File "/home/shatton/hnn_source_code/paramrw.py", line 206, in __read_sim
lines = fio.clean_lines(f_psim)
File "/home/shatton/hnn_source_code/fileio.py", line 205, in clean_lines
with open(file) as f_in:
FileNotFoundError: [Errno 2] No such file or directory: 'Around.param'
[Lola:01853] 7 more processes have sent help message help-btl-vader.txt / cma-permission-denied
[Lola:01853] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
Warning: could not read file: /home/shatton/hnn_out/data/Messing Around/dpl.txt
Warning: could not read file: /home/shatton/hnn_out/data/Messing Around/spk.txt
Warning: could not read file: /home/shatton/hnn_out/data/Messing Around/dpl.txt
Warning: could not read file: /home/shatton/hnn_out/data/Messing Around/spk.txt

**Comment by ntolley** [comment]
Thanks for sending this along @shatton412! 

Unfortunately our ability to troubleshoot may be limited as we are currently transitioning our support to a new GUI with our hnn-core project: https://jonescompneurolab.github.io/hnn-core/stable/index.html

Are you able to run non MPI simulations (using just 1 cpu core)? The issue may have to do with your specific MPI installation based on the air messages

**Comment by rythorpe** [comment]
I think this is an I/O problem actually. @shatton412 try using file names that don't have spaces in them (e.g., "messing_around" instead of "Messing Around"). I'm guessing you're using a Windows machine?

**Comment by shatton412** [comment]
Well I tried that and it worked! Thank you!

**Comment by rythorpe** [comment]
Good to hear. Let us know if you run into anything else!
