### ISSUE TITLE
 Python 11 UI issue: setGeometry(self, a0: QRect): argument 1 has unexpected type 'float'

### ISSUE THREAD

**Issue by filippomc** [jonescompneurolab/hnn#345]
The issue below prevents the loading of the UI with a Python 11 based setup.

```
Traceback (most recent call last):
  File "/opt/user/hnn/hnn_source_code/hnn.py", line 37, in <module>
    runqt5()
  File "/opt/user/hnn/hnn_source_code/hnn.py", line 26, in runqt5
    ex = HNNGUI()
         ^^^^^^^^
  File "/opt/user/hnn/hnn_source_code/hnn_qt5.py", line 3347, in __init__
    self.initUI()
  File "/opt/user/hnn/hnn_source_code/hnn_qt5.py", line 4008, in initUI
    setscalegeomcenter(self, 1500, 1300) # start GUI in center of screenm, scale based on screen w x h 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/user/hnn/hnn_source_code/gutils.py", line 53, in setscalegeomcenter
    dlg.setGeometry(x, y, int(nw), int(nh))
TypeError: arguments did not match any overloaded call:
  setGeometry(self, a0: QRect): argument 1 has unexpected type 'float'
  setGeometry(self, ax: int, ay: int, aw: int, ah: int): argument 1 has unexpected type 'float'
```

**Comment by ntolley** [comment]
Hi @filippomc!

We are actually in the process of moving our development to a new graphical user interface that is accessible through the hnn-core repository: https://github.com/jonescompneurolab/hnn-core

This repository will be archived/deprecated shortly

The GUI is currently available as a pre-release which you can install and run through the following commands:

```
$ pip install --pre hnn_core[gui]
$ hnn-gui
```
There is also a well documented python API to run simulations in the model if that interests you as well! Please let us know if you have any questions

**Comment by filippomc** [comment]
Thanks @ntolley will give it a try!

**Comment by filippomc** [comment]
Hi @ntolley I've tried installing as you suggested and I get this issue when running:

```
Traceback (most recent call last):
...
    raise ImportError(
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
Install lxml[html_clean] or lxml_html_clean directly.
```
After installing lxml[html_clean] this other issue occurs

<img width="452" alt="image" src="https://github.com/user-attachments/assets/1a463ddc-4cc8-45f9-b716-9593cffe47b7">

**Comment by jasmainak** [comment]
Do you get the error when opening the website that Voila asks you to?

**Comment by ntolley** [comment]
Just ran into this as well! It's an error introduced by a recent update to a dependency, will need to investigate further
